labels: []
body:
  - type: markdown
    attributes:
      value: |
        # Describe the issue
  - type: textarea
    id: actualIssue
    attributes:
      label: What is the issue?
      description: "Please give a clear description of the issue you are experiencing."
    validations:
      required: true
  - type: textarea
    id: reproSteps
    attributes:
      label: How can I reproduce this issue?
      description: "Please give an extensive, step-by-step instruction on what I need to do to see the issue myself"
      value: |
        1. Open the app
        2. Open a reminder for editing
        3. ...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        # Some quick questions
        _These questions help me find the issue - and the fix - faster_
  - type: input
    id: statistics-id
    attributes:
      label: Please enter your statistics id
      description: This allows me to view analytics and internal error reports coming from your device. You can find it under 'Statistics' -> 'Your statistics identifier' in the home screen side menu.
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: Which version of Snooze It do you use?
      description: "You can find the version number by tapping 'About' in the home screen side menu. It should look like this: 'v0.2.005 (+55)'"
    validations:
      required: true
  - type: dropdown
    id: frequency
    attributes:
      label: How often does this issue occur?
      options:
        - Only happened once
        - It occurs occasionally
        - It occurs frequently
        - It occurs every time / constantly
    validations:
      required: true
  - type: dropdown
    id: effect-on-usage
    attributes:
      label: How does this issue effect your use of the app?
      options:
        - I can still use the app as I did before
        - There are one or more features I cannot use
        - The app works, but is unreliable 
        - The app is barely usable
        - I cannot use the app at all
    validations:
      required: true

